In [220]:
import os
import numpy as np
import pandas as pd
import pickle
import h5py
from mmsdk import mmdatasdk
from mmsdk.mmdatasdk.computational_sequence.computational_sequence import computational_sequence
from mmsdk.mmdatasdk.dataset.standard_datasets.CMU_MOSEI import cmu_mosei_std_folds

In [4]:
data_dir = 'data/'
data_dir

'data/'

In [7]:
text_csd = computational_sequence(os.path.join(data_dir, 'CMU_MOSEI_TimestampedWordVectors.csd'))

[2025-06-18 02:40:22.991] | Success | Computational sequence read from file data/CMU_MOSEI_TimestampedWordVectors.csd ...
[2025-06-18 02:40:23.032] | Status  | Checking the integrity of the <glove_vectors> computational sequence ...
[2025-06-18 02:40:23.033] | Status  | Checking the format of the data in <glove_vectors> computational sequence ...


[2025-06-18 02:40:23.539] | Success | <glove_vectors> computational sequence data in correct format.
[2025-06-18 02:40:23.539] | Status  | Checking the format of the metadata in <glove_vectors> computational sequence ...
[2025-06-18 02:40:23.539] | Warning | <glove_vectors> computational sequence does not have all the required metadata ... continuing 


In [99]:
import h5py

# 打开 HDF5 文件
file_path = 'data/CMU_MOSEI_TimestampedWordVectors.csd'
with h5py.File(file_path, 'r') as f:
    # 查看所有的顶层键（类似于文件夹/组名）
    print("Keys:", list(f.keys()))
    
    # 假设第一个键是你感兴趣的数据
    first_key = list(f.keys())[0]
    print("First key:", first_key)
    
    # 查看该组下的内容
    group = f[first_key]
    print("Attributes:", dict(group.attrs))
    print("Datasets:", list(group.keys()))
    print(group['data'])

Keys: ['glove_vectors']
First key: glove_vectors
Attributes: {}
Datasets: ['data', 'metadata']
<HDF5 group "/glove_vectors/data" (3837 members)>


In [100]:
text_csd.data.keys()

dict_keys(['--qXJuDtHPw', '-3g5yACwYnA', '-3nNcZdcdvU', '-571d8cVauQ', '-6rXp3zJ3kc', '-9YyBTjo1zo', '-9y-fZ3swSY', '-AUZQgSxyPQ', '-Alixo7euuU', '-Eqdz5y4pEY', '-HeZS2-Prhc', '-HvKLjmsO5U', '-HwX2H8Z4hY', '-IUUR2yyNbw', '-I_e4mIh0yE', '-IqSFQePnpU', '-KCahx2qBOI', '-LnuDPiuuZw', '-MeTTeMJBNc', '-NFrJFQijFE', '-RfYyzHpjk4', '-RpZEe4w4fY', '-SYSVSQnTnA', '-THoVjtIkeU', '-UUCSKoHeMA', '-UacrmKiTn4', '-UuX1xuaiiE', '-VmheDA92mM', '-WXXTNIJcVM', '-ZgjBOA1Yhw', '-a55Q6RWvTA', '-aNfi7CP8vM', '-aqamKhZ1Ec', '-bl5PfNIYrk', '-cEhr0cQcDM', '-cmk6cfUeMs', '-dZ1TCboxcQ', '-dxfTGcXJoc', '-egA8-b7-3M', '-hPfPhUIzfA', '-hnBHBN8p5A', '-iRBcNs9oI8', '-l_53IwQoj0', '-lqc32Zpr7M', '-lzEya4AM_4', '-m9KtvCk_L8', '-mJ2ud6oKI8', '-mqbVkbCndg', '-o_667Ny7RM', '-qDkUB0GgYY', '-qMhGeJkp5o', '-ri04Z7vwnc', '-rxZxtG0xmY', '-s9qJ7ATP7w', '-t217m2on-s', '-tANM6ETl_M', '-tPCytz4rww', '-uywlfIYOS8', '-vxjVxOeScU', '-wMB_hJL-3o', '-wdUIwjDMfg', '-wny0OAz3g8', '-yRb-Jum7EQ', '03X1FwF6udc', '06st0Ez_E_I', '07Z16yRBFUQ',

In [170]:
text_csd.data['-3g5yACwYnA']

<HDF5 group "/glove_vectors/data/-3g5yACwYnA" (2 members)>

In [171]:
text_csd.data['-3g5yACwYnA'].keys()

<KeysViewHDF5 ['features', 'intervals']>

In [172]:
text_csd.data['-3g5yACwYnA']['features'][:]

array([[ 0.028796 ,  0.41306  , -0.4669   , ..., -0.053029 , -0.33494  ,
         0.36282  ],
       [ 0.08649  ,  0.14503  , -0.4902   , ...,  0.25909  , -0.18599  ,
         0.0085633],
       [ 0.23231  , -0.024102 , -0.83964  , ..., -0.11987  ,  0.052277 ,
         0.1449   ],
       ...,
       [ 0.17176  ,  0.51665  ,  0.3556   , ..., -0.022907 , -0.21833  ,
         0.18726  ],
       [-0.30312  ,  0.38081  , -0.14552  , ...,  0.1851   , -0.19091  ,
         0.04195  ],
       [ 0.       ,  0.       ,  0.       , ...,  0.       ,  0.       ,
         0.       ]], shape=(435, 300))

In [173]:
text_csd.data['-3g5yACwYnA']['intervals'][:]

array([[1.24716553e-02, 3.01814059e-01],
       [3.01814059e-01, 4.51473923e-01],
       [4.51473923e-01, 6.60997732e-01],
       [6.60997732e-01, 8.60544218e-01],
       [8.60544218e-01, 1.31950113e+00],
       [1.31950113e+00, 1.71859410e+00],
       [1.71859410e+00, 1.84829932e+00],
       [1.84829932e+00, 2.23741497e+00],
       [2.23741497e+00, 2.77619048e+00],
       [2.77619048e+00, 2.83605442e+00],
       [2.83605442e+00, 3.08548753e+00],
       [3.08548753e+00, 3.52448980e+00],
       [3.52448980e+00, 3.63424036e+00],
       [3.63424036e+00, 3.90362812e+00],
       [3.90362812e+00, 4.39251701e+00],
       [4.39251701e+00, 4.66190476e+00],
       [4.66190476e+00, 5.34036281e+00],
       [5.34036281e+00, 5.40022676e+00],
       [5.40022676e+00, 6.02879819e+00],
       [6.02879819e+00, 6.47777778e+00],
       [6.47777778e+00, 6.74716553e+00],
       [6.74716553e+00, 7.20612245e+00],
       [7.20612245e+00, 7.58526077e+00],
       [7.58526077e+00, 7.70498866e+00],
       [7.704988

In [9]:
audio_csd = computational_sequence(os.path.join(data_dir, 'CMU_MOSEI_COVAREP.csd'))

[2025-06-18 02:42:52.411] | Success | Computational sequence read from file data/CMU_MOSEI_COVAREP.csd ...
[2025-06-18 02:42:52.825] | Status  | Checking the integrity of the <COVAREP> computational sequence ...
[2025-06-18 02:42:52.825] | Status  | Checking the format of the data in <COVAREP> computational sequence ...


[2025-06-18 02:42:53.987] | Success | <COVAREP> computational sequence data in correct format.
[2025-06-18 02:42:53.987] | Status  | Checking the format of the metadata in <COVAREP> computational sequence ...
[2025-06-18 02:42:53.987] | Warning | <COVAREP> computational sequence does not have all the required metadata ... continuing 


In [102]:
import h5py

# 打开 HDF5 文件
file_path = 'data/CMU_MOSEI_COVAREP.csd'
with h5py.File(file_path, 'r') as f:
    # 查看所有的顶层键（类似于文件夹/组名）
    print("Keys:", list(f.keys()))
    
    # 假设第一个键是你感兴趣的数据
    first_key = list(f.keys())[0]
    print("First key:", first_key)
    
    # 查看该组下的内容
    group = f[first_key]
    print("Attributes:", dict(group.attrs))
    print("Datasets:", list(group.keys()))
    print(group['data'])

Keys: ['COVAREP']
First key: COVAREP
Attributes: {}
Datasets: ['data', 'metadata']
<HDF5 group "/COVAREP/data" (3836 members)>


In [16]:
audio_csd.data.keys()

dict_keys(['--qXJuDtHPw', '-3g5yACwYnA', '-3nNcZdcdvU', '-571d8cVauQ', '-6rXp3zJ3kc', '-9YyBTjo1zo', '-9y-fZ3swSY', '-AUZQgSxyPQ', '-Alixo7euuU', '-Eqdz5y4pEY', '-HeZS2-Prhc', '-HvKLjmsO5U', '-HwX2H8Z4hY', '-IUUR2yyNbw', '-I_e4mIh0yE', '-IqSFQePnpU', '-KCahx2qBOI', '-LnuDPiuuZw', '-MeTTeMJBNc', '-NFrJFQijFE', '-RfYyzHpjk4', '-RpZEe4w4fY', '-SYSVSQnTnA', '-THoVjtIkeU', '-UUCSKoHeMA', '-UacrmKiTn4', '-UuX1xuaiiE', '-VmheDA92mM', '-WXXTNIJcVM', '-ZgjBOA1Yhw', '-a55Q6RWvTA', '-aNfi7CP8vM', '-aqamKhZ1Ec', '-bl5PfNIYrk', '-cEhr0cQcDM', '-cmk6cfUeMs', '-dZ1TCboxcQ', '-dxfTGcXJoc', '-egA8-b7-3M', '-hPfPhUIzfA', '-hnBHBN8p5A', '-iRBcNs9oI8', '-l_53IwQoj0', '-lqc32Zpr7M', '-lzEya4AM_4', '-m9KtvCk_L8', '-mJ2ud6oKI8', '-mqbVkbCndg', '-o_667Ny7RM', '-qDkUB0GgYY', '-qMhGeJkp5o', '-ri04Z7vwnc', '-rxZxtG0xmY', '-s9qJ7ATP7w', '-t217m2on-s', '-tANM6ETl_M', '-tPCytz4rww', '-uywlfIYOS8', '-vxjVxOeScU', '-wMB_hJL-3o', '-wdUIwjDMfg', '-wny0OAz3g8', '-yRb-Jum7EQ', '03X1FwF6udc', '06st0Ez_E_I', '07Z16yRBFUQ',

In [174]:
audio_csd.data['-3g5yACwYnA']

<HDF5 group "/COVAREP/data/-3g5yACwYnA" (2 members)>

In [175]:
audio_csd.data['-3g5yACwYnA'].keys()

<KeysViewHDF5 ['features', 'intervals']>

In [176]:
audio_csd.data['-3g5yACwYnA']['features'][:]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(14475, 74), dtype=float32)

In [177]:
audio_csd.data['-3g5yACwYnA']['intervals'][:]

array([[0.0000e+00, 1.0000e-02],
       [1.0000e-02, 2.0000e-02],
       [2.0000e-02, 3.0000e-02],
       ...,
       [1.4472e+02, 1.4473e+02],
       [1.4473e+02, 1.4474e+02],
       [1.4474e+02, 1.4475e+02]], shape=(14475, 2))

In [11]:
video_csd = computational_sequence(os.path.join(data_dir, 'CMU_MOSEI_VisualFacet42.csd'))

[2025-06-18 02:46:21.441] | Success | Computational sequence read from file data/CMU_MOSEI_VisualFacet42.csd ...
[2025-06-18 02:46:21.917] | Status  | Checking the integrity of the <FACET 4.2> computational sequence ...
[2025-06-18 02:46:21.918] | Status  | Checking the format of the data in <FACET 4.2> computational sequence ...


[2025-06-18 02:46:23.406] | Success | <FACET 4.2> computational sequence data in correct format.
[2025-06-18 02:46:23.406] | Status  | Checking the format of the metadata in <FACET 4.2> computational sequence ...
[2025-06-18 02:46:23.406] | Warning | <FACET 4.2> computational sequence does not have all the required metadata ... continuing 


In [58]:
import h5py

# 打开 HDF5 文件
file_path = 'data/CMU_MOSEI_VisualFacet42.csd'
with h5py.File(file_path, 'r') as f:
    # 查看所有的顶层键（类似于文件夹/组名）
    print("Keys:", list(f.keys()))
    
    # 假设第一个键是你感兴趣的数据
    first_key = list(f.keys())[0]
    print("First key:", first_key)
    
    # 查看该组下的内容
    group = f[first_key]
    print("Attributes:", dict(group.attrs))
    print("Datasets:", list(group.keys()))
    print(group['data'])

Keys: ['FACET 4.2']
First key: FACET 4.2
Attributes: {}
Datasets: ['data', 'metadata']
<HDF5 group "/FACET 4.2/data" (3837 members)>


In [63]:
video_csd.data.keys()

dict_keys(['--qXJuDtHPw', '-3g5yACwYnA', '-3nNcZdcdvU', '-571d8cVauQ', '-6rXp3zJ3kc', '-9YyBTjo1zo', '-9y-fZ3swSY', '-AUZQgSxyPQ', '-Alixo7euuU', '-Eqdz5y4pEY', '-HeZS2-Prhc', '-HvKLjmsO5U', '-HwX2H8Z4hY', '-IUUR2yyNbw', '-I_e4mIh0yE', '-IqSFQePnpU', '-KCahx2qBOI', '-LnuDPiuuZw', '-MeTTeMJBNc', '-NFrJFQijFE', '-RfYyzHpjk4', '-RpZEe4w4fY', '-SYSVSQnTnA', '-THoVjtIkeU', '-UUCSKoHeMA', '-UacrmKiTn4', '-UuX1xuaiiE', '-VmheDA92mM', '-WXXTNIJcVM', '-ZgjBOA1Yhw', '-a55Q6RWvTA', '-aNfi7CP8vM', '-aqamKhZ1Ec', '-bl5PfNIYrk', '-cEhr0cQcDM', '-cmk6cfUeMs', '-dZ1TCboxcQ', '-dxfTGcXJoc', '-egA8-b7-3M', '-hPfPhUIzfA', '-hnBHBN8p5A', '-iRBcNs9oI8', '-l_53IwQoj0', '-lqc32Zpr7M', '-lzEya4AM_4', '-m9KtvCk_L8', '-mJ2ud6oKI8', '-mqbVkbCndg', '-o_667Ny7RM', '-qDkUB0GgYY', '-qMhGeJkp5o', '-ri04Z7vwnc', '-rxZxtG0xmY', '-s9qJ7ATP7w', '-t217m2on-s', '-tANM6ETl_M', '-tPCytz4rww', '-uywlfIYOS8', '-vxjVxOeScU', '-wMB_hJL-3o', '-wdUIwjDMfg', '-wny0OAz3g8', '-yRb-Jum7EQ', '03X1FwF6udc', '06st0Ez_E_I', '07Z16yRBFUQ',

In [178]:
video_csd.data['-3g5yACwYnA']

<HDF5 group "/FACET 4.2/data/-3g5yACwYnA" (2 members)>

In [179]:
video_csd.data['-3g5yACwYnA'].keys()

<KeysViewHDF5 ['features', 'intervals']>

In [180]:
video_csd.data['-3g5yACwYnA']['features'][:]

array([[-1.46224e+00, -5.06078e-01, -4.53252e-01, ..., -4.39641e+00,
         1.73280e+01, -3.85878e-01],
       [-1.43509e+00, -6.88686e-01, -2.57139e-01, ..., -5.77265e+00,
         1.67928e+01, -5.75716e-01],
       [-1.45590e+00, -7.99603e-01,  1.19300e-02, ..., -6.61379e+00,
         1.66278e+01, -7.97784e-01],
       ...,
       [-1.41352e+00, -4.75324e-02, -8.78553e-01, ...,  2.40264e+00,
         2.28287e+01, -3.76633e+00],
       [-1.34390e+00, -5.47402e-02, -8.49038e-01, ...,  2.71941e+00,
         2.27106e+01, -3.92612e+00],
       [-1.38143e+00,  1.75267e-01, -1.01821e+00, ...,  2.81532e+00,
         2.23650e+01, -4.34690e+00]], shape=(4340, 35), dtype=float32)

In [181]:
video_csd.data['-3g5yACwYnA']['intervals'][:]

array([[0.00000e+00, 3.33333e-02],
       [3.33333e-02, 6.66667e-02],
       [6.66667e-02, 1.00000e-01],
       ...,
       [1.44567e+02, 1.44600e+02],
       [1.44600e+02, 1.44633e+02],
       [1.44633e+02, 1.44667e+02]], shape=(4340, 2))

In [13]:
labels_csd = computational_sequence(os.path.join(data_dir, 'CMU_MOSEI_Labels.csd'))

[2025-06-18 02:46:48.154] | Success | Computational sequence read from file data/CMU_MOSEI_Labels.csd ...
[2025-06-18 02:46:48.597] | Status  | Checking the integrity of the <All Labels> computational sequence ...
[2025-06-18 02:46:48.598] | Status  | Checking the format of the data in <All Labels> computational sequence ...


[2025-06-18 02:46:49.329] | Success | <All Labels> computational sequence data in correct format.
[2025-06-18 02:46:49.329] | Status  | Checking the format of the metadata in <All Labels> computational sequence ...
[2025-06-18 02:46:49.329] | Warning | <All Labels> computational sequence does not have all the required metadata ... continuing 


In [103]:
import h5py

# 打开 HDF5 文件
file_path = 'data/CMU_MOSEI_Labels.csd'
with h5py.File(file_path, 'r') as f:
    # 查看所有的顶层键（类似于文件夹/组名）
    print("Keys:", list(f.keys()))
    
    # 假设第一个键是你感兴趣的数据
    first_key = list(f.keys())[0]
    print("First key:", first_key)
    
    # 查看该组下的内容
    group = f[first_key]
    print("Attributes:", dict(group.attrs))
    print("Datasets:", list(group.keys()))
    print(group['data'])

Keys: ['All Labels']
First key: All Labels
Attributes: {}
Datasets: ['data', 'metadata']
<HDF5 group "/All Labels/data" (3293 members)>


In [182]:
labels_csd.data.keys()

dict_keys(['--qXJuDtHPw', '-3g5yACwYnA', '-3nNcZdcdvU', '-571d8cVauQ', '-6rXp3zJ3kc', '-9YyBTjo1zo', '-9y-fZ3swSY', '-AUZQgSxyPQ', '-Alixo7euuU', '-Eqdz5y4pEY', '-HeZS2-Prhc', '-HvKLjmsO5U', '-HwX2H8Z4hY', '-IUUR2yyNbw', '-I_e4mIh0yE', '-IqSFQePnpU', '-KCahx2qBOI', '-LnuDPiuuZw', '-MeTTeMJBNc', '-NFrJFQijFE', '-RfYyzHpjk4', '-RpZEe4w4fY', '-SYSVSQnTnA', '-THoVjtIkeU', '-UUCSKoHeMA', '-UacrmKiTn4', '-UuX1xuaiiE', '-VmheDA92mM', '-WXXTNIJcVM', '-ZgjBOA1Yhw', '-a55Q6RWvTA', '-aNfi7CP8vM', '-aqamKhZ1Ec', '-bl5PfNIYrk', '-cEhr0cQcDM', '-cmk6cfUeMs', '-dZ1TCboxcQ', '-dxfTGcXJoc', '-egA8-b7-3M', '-hPfPhUIzfA', '-hnBHBN8p5A', '-iRBcNs9oI8', '-l_53IwQoj0', '-lqc32Zpr7M', '-lzEya4AM_4', '-m9KtvCk_L8', '-mJ2ud6oKI8', '-mqbVkbCndg', '-o_667Ny7RM', '-qDkUB0GgYY', '-qMhGeJkp5o', '-ri04Z7vwnc', '-rxZxtG0xmY', '-s9qJ7ATP7w', '-t217m2on-s', '-tANM6ETl_M', '-tPCytz4rww', '-uywlfIYOS8', '-vxjVxOeScU', '-wMB_hJL-3o', '-wdUIwjDMfg', '-wny0OAz3g8', '-yRb-Jum7EQ', '03X1FwF6udc', '06st0Ez_E_I', '07Z16yRBFUQ',

In [183]:
labels_csd.data['-3g5yACwYnA']

<HDF5 group "/All Labels/data/-3g5yACwYnA" (2 members)>

In [184]:
labels_csd.data['-3g5yACwYnA'].keys()

<KeysViewHDF5 ['features', 'intervals']>

In [185]:
labels_csd.data['-3g5yACwYnA']['features'][:]

array([[1.        , 0.6666667 , 0.6666667 , 0.        , 0.        ,
        0.        , 0.6666667 ],
       [0.6666667 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.6666667 , 0.6666667 , 0.        , 0.        ,
        0.        , 0.33333334],
       [0.        , 0.33333334, 0.33333334, 0.        , 0.        ,
        0.        , 0.        ],
       [1.        , 0.6666667 , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.6666667 , 0.        , 0.6666667 , 0.        , 0.        ,
        0.        , 0.33333334]], dtype=float32)

In [186]:
labels_csd.data['-3g5yACwYnA']['intervals'][:]

array([[ 82.753, 100.555],
       [119.919, 125.299],
       [  4.84 ,  14.052],
       [ 13.211,  27.521],
       [ 26.541,  41.3  ],
       [ 74.083,  82.776]])

In [164]:
visual_field = 'CMU_MOSEI_VisualFacet42'
acoustic_field = 'CMU_MOSEI_COVAREP'
text_field = 'CMU_MOSEI_TimestampedWordVectors'
label_field = 'CMU_MOSEI_Labels'

features = [
    text_field, 
    visual_field, 
    acoustic_field
]

recipe = {feat: os.path.join(data_dir, feat) + '.csd' for feat in features}
dataset = mmdatasdk.mmdataset(recipe)
dataset

[2025-06-18 06:17:07.212] | Success | Computational sequence read from file data/CMU_MOSEI_TimestampedWordVectors.csd ...
[2025-06-18 06:17:07.468] | Status  | Checking the integrity of the <glove_vectors> computational sequence ...
[2025-06-18 06:17:07.468] | Status  | Checking the format of the data in <glove_vectors> computational sequence ...


[2025-06-18 06:17:08.021] | Success | <glove_vectors> computational sequence data in correct format.
[2025-06-18 06:17:08.022] | Status  | Checking the format of the metadata in <glove_vectors> computational sequence ...
[2025-06-18 06:17:08.022] | Warning | <glove_vectors> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 06:17:08.022] | Success | Computational sequence read from file data/CMU_MOSEI_VisualFacet42.csd ...
[2025-06-18 06:17:08.056] | Status  | Checking the integrity of the <FACET 4.2> computational sequence ...
[2025-06-18 06:17:08.056] | Status  | Checking the format of the data in <FACET 4.2> computational sequence ...


[2025-06-18 06:17:08.578] | Success | <FACET 4.2> computational sequence data in correct format.
[2025-06-18 06:17:08.578] | Status  | Checking the format of the metadata in <FACET 4.2> computational sequence ...
[2025-06-18 06:17:08.578] | Warning | <FACET 4.2> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 06:17:08.578] | Success | Computational sequence read from file data/CMU_MOSEI_COVAREP.csd ...
[2025-06-18 06:17:08.613] | Status  | Checking the integrity of the <COVAREP> computational sequence ...
[2025-06-18 06:17:08.613] | Status  | Checking the format of the data in <COVAREP> computational sequence ...


[2025-06-18 06:17:09.180] | Success | <COVAREP> computational sequence data in correct format.
[2025-06-18 06:17:09.180] | Status  | Checking the format of the metadata in <COVAREP> computational sequence ...
[2025-06-18 06:17:09.180] | Warning | <COVAREP> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 06:17:09.180] | Success | Dataset initialized successfully ... 


In [165]:
# Take a look into the dataset
print(list(dataset.keys()))
print("=" * 80)

print(list(dataset[visual_field].keys())[:10])
print("=" * 80)

some_id = list(dataset[visual_field].keys())[15]
print(list(dataset[visual_field][some_id].keys()))
print("=" * 80)

print(list(dataset[visual_field][some_id]['intervals'].shape))
print("=" * 80)

print(list(dataset[visual_field][some_id]['features'].shape))
print(list(dataset[text_field][some_id]['features'].shape))
print(list(dataset[acoustic_field][some_id]['features'].shape))
print("Different modalities have different number of time steps!")

['CMU_MOSEI_TimestampedWordVectors', 'CMU_MOSEI_VisualFacet42', 'CMU_MOSEI_COVAREP']
['--qXJuDtHPw', '-3g5yACwYnA', '-3nNcZdcdvU', '-571d8cVauQ', '-6rXp3zJ3kc', '-9YyBTjo1zo', '-9y-fZ3swSY', '-AUZQgSxyPQ', '-Alixo7euuU', '-Eqdz5y4pEY']
['features', 'intervals']
[3658, 2]
[3658, 35]
[321, 300]
[12209, 74]
Different modalities have different number of time steps!


In [168]:
# Align
# we define a simple averaging function that does not depend on intervals
def avg(intervals: np.array, features: np.array) -> np.array:
    try:
        return np.average(features, axis=0)
    except:
        return features

# first we align to words with averaging, collapse_function receives a list of functions
dataset.align(text_field, collapse_functions=[avg])

[2025-06-18 06:18:54.942] | Status  | Unify was called ...
[2025-06-18 06:18:54.945] | Warning | PEBwwe0PLZ8 entry is not shared among all sequences, removing it ...
[2025-06-18 06:18:54.946] | Success | Unify completed ...
[2025-06-18 06:18:54.946] | Status  | Pre-alignment based on <CMU_MOSEI_TimestampedWordVectors> computational sequence started ...
[2025-06-18 06:19:09.621] | Status  | Pre-alignment done for <CMU_MOSEI_VisualFacet42> ...
[2025-06-18 06:20:37.843] | Status  | Pre-alignment done for <CMU_MOSEI_COVAREP> ...
[2025-06-18 06:21:11.978] | Status  | Alignment starting ...


[2025-06-18 07:49:24.807] | Success | Alignment to <CMU_MOSEI_TimestampedWordVectors> complete.
[2025-06-18 07:49:24.808] | Status  | Replacing dataset content with aligned computational sequences
[2025-06-18 07:49:25.050] | Success | Initialized empty <CMU_MOSEI_TimestampedWordVectors> computational sequence.
[2025-06-18 07:49:25.051] | Status  | Checking the format of the data in <CMU_MOSEI_TimestampedWordVectors> computational sequence ...


[2025-06-18 07:49:28.253] | Success | <CMU_MOSEI_TimestampedWordVectors> computational sequence data in correct format.
[2025-06-18 07:49:28.253] | Status  | Checking the format of the metadata in <CMU_MOSEI_TimestampedWordVectors> computational sequence ...
[2025-06-18 07:49:28.255] | Warning | <CMU_MOSEI_TimestampedWordVectors> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:49:28.255] | Success | Initialized empty <CMU_MOSEI_VisualFacet42> computational sequence.
[2025-06-18 07:49:28.255] | Status  | Checking the format of the data in <CMU_MOSEI_VisualFacet42> computational sequence ...


[2025-06-18 07:49:28.956] | Success | <CMU_MOSEI_VisualFacet42> computational sequence data in correct format.
[2025-06-18 07:49:28.956] | Status  | Checking the format of the metadata in <CMU_MOSEI_VisualFacet42> computational sequence ...
[2025-06-18 07:49:28.956] | Warning | <CMU_MOSEI_VisualFacet42> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:49:28.956] | Success | Initialized empty <CMU_MOSEI_COVAREP> computational sequence.
[2025-06-18 07:49:28.965] | Status  | Checking the format of the data in <CMU_MOSEI_COVAREP> computational sequence ...


[2025-06-18 07:49:29.640] | Success | <CMU_MOSEI_COVAREP> computational sequence data in correct format.
[2025-06-18 07:49:29.640] | Status  | Checking the format of the metadata in <CMU_MOSEI_COVAREP> computational sequence ...
[2025-06-18 07:49:29.645] | Warning | <CMU_MOSEI_COVAREP> computational sequence does not have all the required metadata ... continuing 


In [187]:
# Add labels

# we add and align to lables to obtain labeled segments
# this time we don't apply collapse functions so that the temporal sequences are preserved
label_recipe = {label_field: os.path.join(data_dir, label_field + '.csd')}
dataset.add_computational_sequences(label_recipe, destination=None)
dataset.align(label_field)

# check out what the keys look like now
print(list(dataset[text_field].keys())[55])

[2025-06-18 07:51:37.868] | Success | Computational sequence read from file data/CMU_MOSEI_Labels.csd ...
[2025-06-18 07:51:37.940] | Status  | Checking the integrity of the <All Labels> computational sequence ...
[2025-06-18 07:51:37.940] | Status  | Checking the format of the data in <All Labels> computational sequence ...


[2025-06-18 07:51:38.962] | Success | <All Labels> computational sequence data in correct format.
[2025-06-18 07:51:38.962] | Status  | Checking the format of the metadata in <All Labels> computational sequence ...
[2025-06-18 07:51:38.962] | Warning | <All Labels> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:51:38.963] | Status  | Unify was called ...
[2025-06-18 07:51:39.862] | Warning | 110794 entry is not shared among all sequences, removing it ...
[2025-06-18 07:51:40.104] | Warning | vi0FsBCqfRE entry is not shared among all sequences, removing it ...
[2025-06-18 07:51:40.347] | Warning | 255205 entry is not shared among all sequences, removing it ...
[2025-06-18 07:51:40.594] | Warning | 187566 entry is not shared among all sequences, removing it ...
[2025-06-18 07:51:40.857] | Warning | 17622 entry is not shared among all sequences, removing it ...
[2025-06-18 07:51:41.126] | Warning | 110690 entry is not shared among all sequenc

[2025-06-18 07:54:30.913] | Success | Alignment to <CMU_MOSEI_Labels> complete.
[2025-06-18 07:54:30.914] | Status  | Replacing dataset content with aligned computational sequences
[2025-06-18 07:54:34.319] | Success | Initialized empty <CMU_MOSEI_TimestampedWordVectors> computational sequence.
[2025-06-18 07:54:34.319] | Status  | Checking the format of the data in <CMU_MOSEI_TimestampedWordVectors> computational sequence ...


[2025-06-18 07:54:34.341] | Success | <CMU_MOSEI_TimestampedWordVectors> computational sequence data in correct format.
[2025-06-18 07:54:34.341] | Status  | Checking the format of the metadata in <CMU_MOSEI_TimestampedWordVectors> computational sequence ...
[2025-06-18 07:54:34.341] | Warning | <CMU_MOSEI_TimestampedWordVectors> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:54:34.341] | Success | Initialized empty <CMU_MOSEI_VisualFacet42> computational sequence.
[2025-06-18 07:54:34.341] | Status  | Checking the format of the data in <CMU_MOSEI_VisualFacet42> computational sequence ...


[2025-06-18 07:54:34.365] | Success | <CMU_MOSEI_VisualFacet42> computational sequence data in correct format.
[2025-06-18 07:54:34.365] | Status  | Checking the format of the metadata in <CMU_MOSEI_VisualFacet42> computational sequence ...
[2025-06-18 07:54:34.365] | Warning | <CMU_MOSEI_VisualFacet42> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:54:34.365] | Success | Initialized empty <CMU_MOSEI_COVAREP> computational sequence.
[2025-06-18 07:54:34.365] | Status  | Checking the format of the data in <CMU_MOSEI_COVAREP> computational sequence ...


[2025-06-18 07:54:34.390] | Success | <CMU_MOSEI_COVAREP> computational sequence data in correct format.
[2025-06-18 07:54:34.390] | Status  | Checking the format of the metadata in <CMU_MOSEI_COVAREP> computational sequence ...
[2025-06-18 07:54:34.390] | Warning | <CMU_MOSEI_COVAREP> computational sequence does not have all the required metadata ... continuing 
[2025-06-18 07:54:34.390] | Success | Initialized empty <CMU_MOSEI_Labels> computational sequence.
[2025-06-18 07:54:34.390] | Status  | Checking the format of the data in <CMU_MOSEI_Labels> computational sequence ...


[2025-06-18 07:54:34.411] | Success | <CMU_MOSEI_Labels> computational sequence data in correct format.
[2025-06-18 07:54:34.411] | Status  | Checking the format of the metadata in <CMU_MOSEI_Labels> computational sequence ...
[2025-06-18 07:54:34.411] | Warning | <CMU_MOSEI_Labels> computational sequence does not have all the required metadata ... continuing 
-HwX2H8Z4hY[4]


In [188]:
# Save the dataset.
with open('data/aligned_mosei.pkl', 'wb') as f:
    pickle.dump(dataset, f)

In [ ]:
with open('data/aligned_mosei.pkl', 'rb') as f:
    data = pickle.load(f)

print(type(data))
print(data.keys() if hasattr(data, 'keys') else data)

<class 'mmsdk.mmdatasdk.dataset.dataset.mmdataset'>
dict_keys(['CMU_MOSEI_TimestampedWordVectors', 'CMU_MOSEI_VisualFacet42', 'CMU_MOSEI_COVAREP', 'CMU_MOSEI_Labels'])


In [205]:
len(data['CMU_MOSEI_Labels'].data)

23248

In [206]:
data['CMU_MOSEI_Labels'].data

{'--qXJuDtHPw[0]': {'intervals': array([[23.199, 30.325]]),
  'features': array([[1.       , 0.6666667, 0.       , 0.       , 0.       , 0.       ,
          0.       ]], dtype=float32)},
 '-3g5yACwYnA[0]': {'intervals': array([[ 82.753, 100.555]]),
  'features': array([[1.       , 0.6666667, 0.6666667, 0.       , 0.       , 0.       ,
          0.6666667]], dtype=float32)},
 '-3g5yACwYnA[1]': {'intervals': array([[119.919, 125.299]]),
  'features': array([[0.6666667, 0.       , 0.       , 0.       , 0.       , 0.       ,
          0.       ]], dtype=float32)},
 '-3g5yACwYnA[2]': {'intervals': array([[ 4.84 , 14.052]]),
  'features': array([[0.        , 0.6666667 , 0.6666667 , 0.        , 0.        ,
          0.        , 0.33333334]], dtype=float32)},
 '-3g5yACwYnA[3]': {'intervals': array([[13.211, 27.521]]),
  'features': array([[0.        , 0.33333334, 0.33333334, 0.        , 0.        ,
          0.        , 0.        ]], dtype=float32)},
 '-3g5yACwYnA[4]': {'intervals': array([[2

In [198]:
data['CMU_MOSEI_TimestampedWordVectors'].data['-3g5yACwYnA[0]']

{'intervals': array([[ 82.753     ,  83.25328798],
        [ 83.25328798,  83.50272109],
        [ 83.50272109,  83.6324263 ],
        [ 83.6324263 ,  83.86190476],
        [ 83.86190476,  83.99160998],
        [ 83.99160998,  84.55034014],
        [ 84.55034014,  84.94943311],
        [ 84.94943311,  85.28866213],
        [ 85.28866213,  85.41836735],
        [ 85.41836735,  85.60793651],
        [ 85.60793651,  85.94716553],
        [ 85.94716553,  86.27641723],
        [ 86.27641723,  86.35623583],
        [ 86.35623583,  86.74535147],
        [ 86.74535147,  86.95487528],
        [ 86.95487528,  87.52358277],
        [ 87.52358277,  87.84285714],
        [ 87.84285714,  88.06235828],
        [ 88.06235828,  88.33174603],
        [ 88.33174603,  89.02018141],
        [ 89.02018141,  89.23968254],
        [ 89.23968254,  89.66870748],
        [ 89.66870748,  90.0478458 ],
        [ 90.0478458 ,  91.56439909],
        [ 91.56439909,  92.24285714],
        [ 92.24285714,  92.61201814],

In [199]:
data['CMU_MOSEI_VisualFacet42'].data['-3g5yACwYnA[0]']

{'intervals': array([[ 82.753     ,  83.25328798],
        [ 83.25328798,  83.50272109],
        [ 83.50272109,  83.6324263 ],
        [ 83.6324263 ,  83.86190476],
        [ 83.86190476,  83.99160998],
        [ 83.99160998,  84.55034014],
        [ 84.55034014,  84.94943311],
        [ 84.94943311,  85.28866213],
        [ 85.28866213,  85.41836735],
        [ 85.41836735,  85.60793651],
        [ 85.60793651,  85.94716553],
        [ 85.94716553,  86.27641723],
        [ 86.27641723,  86.35623583],
        [ 86.35623583,  86.74535147],
        [ 86.74535147,  86.95487528],
        [ 86.95487528,  87.52358277],
        [ 87.52358277,  87.84285714],
        [ 87.84285714,  88.06235828],
        [ 88.06235828,  88.33174603],
        [ 88.33174603,  89.02018141],
        [ 89.02018141,  89.23968254],
        [ 89.23968254,  89.66870748],
        [ 89.66870748,  90.0478458 ],
        [ 90.0478458 ,  91.56439909],
        [ 91.56439909,  92.24285714],
        [ 92.24285714,  92.61201814],

In [200]:
data['CMU_MOSEI_Labels'].data['-3g5yACwYnA[0]']

{'intervals': array([[ 82.753, 100.555]]),
 'features': array([[1.       , 0.6666667, 0.6666667, 0.       , 0.       , 0.       ,
         0.6666667]], dtype=float32)}